# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
favicon: assets/knightfavicon.ico

# Content configuration version
version: 2

# Personal info
name: Kyriakos Schwarz
title: 
#email: 
# email_title: Email (Email title override)
#phone: 
# phone_title: Phone (Phone title override)
#website: 
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: tr3quart1sta
github_username:  kyriakosschwarz
#stackoverflow_username: "00000001"
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
linkedin_username: kyriakos-schwarz
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#orcid_username: 0000-0000-0000-0000
googlescholar_username: KTWPFIEAAAAJ

# Additional icon links
additional_links:
- title: Lichess
  icon: fas fa-chess-knight
  url: https://lichess.org/@/anelka39
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
#about_title: About
about_profile_image: images/Ibwwnh8n_400x400.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm Kyriakos. I like building things. I have a curious spirit, a solid programming background and I'm fluent in a variety of languages. I am a PhD student in Biomedical Informatics at the University of Zurich. My areas of research cover <mark>Bioinformatics</mark>, <mark>Deep Learning</mark> and <mark>Computational Pharmacology</mark>. In my free time I like to engage myself with Chess, Bouldering and Guitar.
  
#  Write an awesome description about yourself here, this supports markdown, so you can add [links](http://foobar.com) and highlight things <mark>like this</mark>.

#  You can even add paragraphs by using empty lines like this and add anything else [markdown](https://www.markdownguide.org/getting-started#what-is-markdown) supports such as
#    - Lists
#    - Tables
#    - <a href="google.com">Links</a>
#    - Images ![alt text](/images/landscape-trees.jpg "Trees")

content:
  - title: Computational Pharmacology # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border:   # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: "AttentionDDI: Siamese attention-based deep learning method for drug–drug interaction predictions"
#        link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
#        link_text: Link Text
        additional_links:
          - title:  Code
            icon: fab fa-github
            url: https://github.com/uzh-dqbm-cmi/side-effects/
          - title:  Paper
            icon: fas fa-graduation-cap
            url: https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-021-04325-y
        quote: >
          Improving drug-drug interaction predictions with a novel Transformer-based model.
        description: | # this will include new lines to allow paragraphs
          I developed a novel Deep Learning architecture - <mark>AttentionDDI</mark> - in <mark>PyTorch</mark> for the prediction of previously unknown medication side effects. The model is <mark>Transformer</mark>-based and through an <mark>Attention</mark> mechanism it provides explainability over which input data modality (chemical structures, side effects, targets, etc.) is weighted more for improved predictions.
          
          ![Transformer model](https://www.tensorflow.org/images/tutorials/transformer/multi_head_attention.png "Transformer model")
  - title: Bioinformatics # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: "Long non-coding RNA structure estimations for cancer genomics"
#        link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
#        link_text: Link Text
        additional_links:
#          - title:  Code
#            icon: fab fa-github
#            url: https://bitbucket.org/kyriakosschwarz/muehle/src/fb59a339d3655c9b8006caaa64b2a99fa5099e72/
          - title:  Paper
            icon: fas fa-graduation-cap
            url: https://www.biorxiv.org/content/10.1101/2021.11.06.467555
        quote: >
          RNA secondary structure calculation for the identification of cancer driver lncRNAs.
        description: | # this will include new lines to allow paragraphs
          Computational methods that have aimed to predict cancer driver lncRNA genes have thus far relied on scores that do not specifically reflect the lncRNA biology. Therefore, Functional Impact scores, such as conservation scores or base pairing probabilties from RNA secondary structure can be included to improve those predictions. In this project I calculated lncRNA base pairing probabilities and correlated them with conservation scores to examine whether secondary structure is suggestive of gene function.
          
          ![Trans mod](images/rnafold.png "RNA secondary structure")
      - layout: left
        border:   # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: "EM algorithm for genomic methylation profiles"
#        link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
#        link_text: Link Text
        additional_links:
          - title:  Code
            icon: fab fa-github
            url: https://bitbucket.org/jennifer_semple/emclassifier/src/master/
#          - title:  Paper
#            icon: fas fa-graduation-cap
#            url: https://www.biorxiv.org/content/10.1101/2021.11.06.467555
        quote: >
          Implementation of an Expectation-Maximization algorithm for promoter states in C. elegans.
        description: | # this will include new lines to allow paragraphs
          In <i>C. elegans</i> the expression of X-linked genes is downregulated by half by modifying transcription initiation. Here, a EM algorithm was applied to a dataset containing the positions and the methylation status of Cytonsines around the TSS of various genes. The algorithm is written in <mark>R</mark>.
          
          ![TSS methylation](images/EM.png "TSS methylation")
  - title: Web Development # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: "Professional company websites"
#        link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
#        link_text: Link Text
        additional_links:
          - title:  Link
            icon: fas fa-external-link-alt
            url: https://www.fastforward.ch/fastforward/references.html
#          - title:  Paper
#            icon: fas fa-graduation-cap
#            url: https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-021-04325-y
        quote: >
          Professional development of major Swiss company websites.
        description: | # this will include new lines to allow paragraphs
          While working as a software / web developer at <a href="https://www.fastforward.ch/fastforward.html">fastforward websolutions</a> I was involved in the implementation and maintenance of professional company websites. Some notable examples include:
            - <a href="https://www.fastforward.ch/fastforward/references/sympany.html">Sympany</a>
            - <a href="https://www.fastforward.ch/fastforward/references/prosenectute.html">Pro Senectute</a>
            - <a href="https://www.fastforward.ch/fastforward/references/schweizmobilplus.html">SchweizMobil Plus</a>
          
          My responsibilities included web development in <mark>HTML/CSS/JS</mark>, <mark>Magnolia</mark> CMS configuration, extension of CMS functionality in <mark>Java</mark>, setting up <mark>REST/SOAP</mark> services and planning <mark>Agile/Scrum</mark> tasks and sprints. 

      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: "Flurnamen Puzzle"
#        link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
#        link_text: Link Text
#        additional_links:
#          - title:  Code
#            icon: fas fa-external-link-alt
#            url: https://www.fastforward.ch/fastforward/references.html
#          - title:  Paper
#            icon: fas fa-graduation-cap
#            url: https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-021-04325-y
        quote: >
          Web-based puzzle game for primary school students.
        description: | # this will include new lines to allow paragraphs
          An interactive and educational game where local map regions act as puzzle pieces. The primary school students of Läufelfingen can use it to better learn their region in a fun way by piecing together these puzzle pieces. The game was developed with <mark>Processing.js</mark>.
          
          ![Puzzle Game](images/flurnamen.png "Puzzle Game")
      - layout: left
        border:   # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: "Nine men's morris (Mühle) web game"
#        link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
#        link_text: Link Text
        additional_links:
          - title:  Code
            icon: fab fa-github
            url: https://bitbucket.org/kyriakosschwarz/muehle/src/fb59a339d3655c9b8006caaa64b2a99fa5099e72/
#          - title:  Paper
#            icon: fas fa-graduation-cap
#            url: https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-021-04325-y
        quote: >
          A simple and fun web game written in pure JS.
        description: | # this will include new lines to allow paragraphs
          A toy project where I implemented the nine men's morris game (Mühle) with pure <mark>HTML/CSS/JS</mark>.
          
          ![Muehle Game](images/muehle2.png "Muehle Game")
  - title: "Computer Vision & Graphics" # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: "Pidgeon Detection"
#        link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
#        link_text: Link Text
        additional_links:
          - title:  Code
            icon: fab fa-github
            url: https://bitbucket.org/kyriakosschwarz/taubenabwehr/src/master/Taubenabwehr/
#          - title:  Paper
#            icon: fas fa-graduation-cap
#            url: https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-021-04325-y
        quote: >
          Video analysis algorithm for the detection and positioning of pidgeons.
        description: | # this will include new lines to allow paragraphs
          A video analysis algorithm that is based on basic computer vision principles. Based on pidgeon characteristics (shape, size, movement, etc.) their position is determined within a video input stream. Written in <mark>Python/OpenCV/QT</mark>. The video input can be opened in a QT window and areas of interest (detection) can be selected (drawing polygons). Within these areas the positions of detected pidgeons are reported.
          
          ![Pidgeon Detection](https://hackster.imgix.net/uploads/attachments/929293/picture_oKHxX5hcUc.PNG?auto=compress%2Cformat&w=900&h=675&fit=min "Pidgeon Detection")
      - layout: left
        border:   # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: "L-Systems"
#        link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
#        link_text: Link Text
#        additional_links:
#          - title:  Code
#            icon: fab fa-github
#            url: https://bitbucket.org/kyriakosschwarz/taubenabwehr/src/master/Taubenabwehr/
#          - title:  Paper
#            icon: fas fa-graduation-cap
#            url: https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-021-04325-y
        quote: >
          Computer generated trees and fractals through L-Systems.
        description: | # this will include new lines to allow paragraphs
          <a href="https://en.wikipedia.org/wiki/L-system">L-Systems</a> are simple rule-based text generation systems. After the text is generated it can be utilized as instructions of <a href="https://en.wikipedia.org/wiki/Turtle_graphics">Turtle graphics</a>. These turtle graphics then were implemented in <mark>Java</mark> and <mark>OpenGL</mark> in order to draw trees and other fractals.
          
          ![L-System](images/Lsystem.png "L-System")

#  - title: Experience
#    layout: list
#    content:
#      - layout: right
#        title: Company name
#        sub_title: Job title
#        caption: Date Range (eg. November 2016 - present)
#        link: Link to company (optional)
#        quote: >
#          Short description of the company (optional)
#        description: | # this will include new lines to allow paragraphs
#          Description of role
#  - title: Education
#    layout: list
#    content:
#      - layout: top-right
#        title: Institution name
#        sub_title: Qualifications (eg. BA Performing Arts)
#        caption: Date Range (eg. 2016 - 2019)
#        quote: >
#          Short institution or course description (optional)
#        description: | # this will include new lines to allow paragraphs
#          Description of qualification
#  - title: A Little More About Me
#    layout: text
#    content: | # this will include new lines to allow paragraphs
#      This is where you can write a little more about yourself. You could title this section **Interests** and include some of your other interests.
#
#      Or you could title it **Skills** and write a bit more about things that make you more desirable, like *leadership* or *teamwork*

# Footer
# footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
